# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2fca7a21da1c11187553e9020b281bdc085dc4566dd557a47a58d72d5e126a6d3aacffbec7b6359acd9cbd36fbd042b6516e4ba65a680a37fa6d2ee0a35ed39b

test:
  secret_key_base: b3599f650738e8ed1896476a51ba5c439bd5133999e315952eb3cc15342601fc1f6cc756841dcc67a0546de4ef69d3fb17b4953135248235df10d37b1e5a870b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
